# Generated by Django 6.0 on 2025-12-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='git_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
