# Generated by Django 6.0 on 2025-12-16 17:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem_principal',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projetoimagens',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
